server:
  port: 9090

spring:
  application:
    name: workload-service
  datasource:
    url: jdbc:h2:mem:workloaddb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  data:
    mongodb:
      uri: mongodb://localhost:27017/workloads
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    listener:
      concurrency: 2-5 # 2 consumers min, up to 5
      acknowledge-mode: auto

messaging:
  queues:
    training-events: training.workload.events

logging:
  level:
    root: INFO
    com.example.workload: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [tx=%X{txId}] %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

security:
  jwt:
    issuer: gym-crm
    secret: dev-secret-please-change
    audience: internal-services
    leeway-seconds: 30

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka